services:
  yoto-api:
    build: ./app
    container_name: yoto_downloader
    restart: unless-stopped
    ports:
      - "8000:8000" # 暴露给局域网的端口
    volumes:
      # 将 NAS 的实际存放路径映射到容器内的 /downloads
      - ./downloads:/downloads
    environment:
      - TZ=America/Los_Angeles