services:
  yoto-api:
    image: yang517/yoto-downloader:latest
    container_name: yoto_downloader
    restart: unless-stopped
    ports:
      - "8000:8000" # 暴露给局域网的端口
    volumes:
      - ${DOWNLOAD_PATH}:/downloads
      - ${LOG_PATH}:/logs
    environment:
      - TZ=America/Los_Angeles
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL:-}
    user: "${PUID}:${PGID}"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
