services:
  yoto-api:
    build: ./app
    container_name: yoto_downloader
    restart: unless-stopped
    ports:
      - "8000:8000" # 暴露给局域网的端口
    volumes:
      # 读取 .env 中的 DOWNLOAD_PATH 变量
      - ${DOWNLOAD_PATH}:/downloads
    environment:
      - TZ=America/Los_Angeles
    user: "${PUID}:${PGID}"